name: meraki_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-191.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0

  cupertino_icons: ^1.0.8
  meta: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/splash_image.png
    - lib/assets/images/burger.jpg
    - lib/assets/images/SFBClasica.jpg
    - lib/assets/images/SFBCrispyChicken.jpg
    - lib/assets/images/SFBDoubleQuarterPounder.jpg
    - lib/assets/images/asado_pollo.png
    - lib/assets/images/BBQ_pizza.jpg
    - lib/assets/images/bbq_pollo.png
    - lib/assets/images/CHEESE-PEPPERONI.png
    - lib/assets/images/hawaiian_pizza.png
    - lib/assets/images/Pizza_Margherita.png
    - lib/assets/images/pollo_brasa.png
    - lib/assets/images/pollo_frito.png
    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
